server:
  port: 8082  #这里的端口要换，启动两个不同的服务
spring:
  thymeleaf:
    prefix: classpath:/templates/
  redis:
    host: www.azhu.work
    port: 6379
    password:
  session:
    store-type: redis # spring session使用存储类型